import { StyleSheet } from "react-native";
import Colors from "../../assets/styles/Colors";
import ComponentsStyle from "../../assets/styles/Components";

export default StyleSheet.create({
  Container: {
    width: "100%",
    height: "100%",
    padding: 20,
  },
  ProfileHeader: {
    paddingTop: 35,
    flexDirection: "row",
    justifyContent: "space-around",
  },
  Descriprion: {
    width: "70%",
    paddingVertical: 20,
    textAlign: "center",
    color: "gray",
    alignSelf: "center",
    fontSize: 12,
  },

  // Profile Info
  UserName: {
    fontSize: 30,
    color: "gray",
    // marginLeft: 20,
    fontWeight: "bold",
  },
  ProileInfo: ComponentsStyle.Card,
  //   ProileInfo: {
  //   height: "auto",
  //   padding: 15,
  //   paddingTop: 20,
  //   borderRadius: 8,
  //   marginBottom: 5,
  //   elevation: 4,
  // },
  InfoIconContainer: {
    width: "15%",
    justifyContent: "center",
    alignItems: "center",
  },
  InfoItem: {
    marginTop: 2,
    marginBottom: 2,
    flexDirection: "row",
    // backgroundColor: "green",
  },
  InfoIcon: {
    marginTop: "auto",
    marginBottom: "auto",
    marginLeft: 10,
    marginRight: 5,
    // backgroundColor: 'green'
  },
  InfoTitle: {
    color: "#777777",
    marginLeft: 20,
    fontSize: 11,
    fontFamily: "Poppins_600SemiBold",
  },
  Info: {
    width: "100%",
    color: "#BDBDBD",
    marginLeft: 20,
    fontSize: 14,
    fontFamily: "Poppins_400Regular",
  },
  EditButton: {
    width: 40,
    height: 40,
    borderRadius: 40 / 2,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#7F5DF0",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.5,
    elevation: 5,
    alignSelf: "flex-end",
  },
  BioDescription: {
    fontSize: 12,
    width: "80%",
    // backgroundColor: "red",
    paddingTop: 10,
    color: "#BDBDBD",
    alignSelf: "center",
  },
  ImagesArea: {
    flexDirection: "row",
    justifyContent: "space-around",
    height: 240,
  },
  ImageAction: {
    position: "relative",
    bottom: 45,
    marginLeft: "auto",
    marginRight: "auto",
    flexDirection: "row",
    width: 90,
    padding: 7,
    backgroundColor: "rgba(52, 52, 52, 0.6)",
    borderRadius: 50,
  },
  MainImage: {
    height: "100%",
    width: 160,
    borderRadius: 10,
  },
  Image: {
    height: 120,
    width: 100,
    borderRadius: 10,
  },
  FixedArea: {
    backgroundColor: "white",
    position: "absolute",
    bottom: 0,
    width: "100%",
    paddingVertical: 20,
  },
  MainButton: {
    width: "80%",
    margin: "auto",
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 12,
    elevation: 3,
    backgroundColor: "#FF0031",
  },
  text: {
    display: "flex",
    flexDirection: "row",
  },

  // Hobbies
  TitleArea: {
    flexDirection: "row",
    paddingLeft: 15,
    paddingVertical: 5,
    alignItems: "center",
  },
  HobbiesArea: {
    width: "100%",
    // backgroundColor: "green",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    flexWrap: "wrap",
    marginTop: 5,
  },
  Hobbie: {
    borderWidth: 0.1,
    paddingHorizontal: 10,
    width: "45%",
    height: 35,
    margin: 5,
    borderRadius: 50,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
});
